const appConfig = {
    appName: '微仔的奇遇地图',
    mode: 'special', // 预留: special | general
    specialTopicTitle: '社团文化节奇遇周',
    specialTopicSubtitle: '今天和微仔一起去校园里逛逛吧',
    mascotImage: '/assets/images/mascot-weizai.png',
    defaultBannerImage: '/assets/images/banner-default.png',
    emptyStateImage: '/assets/images/empty-default.png',
    generalDataEntry: 'general-campus-entry',
    topicConfigs: {
        special: {
            id: 'club-festival-week',
            title: '社团文化节奇遇周',
            subtitle: '点一点地图，看看哪儿有新鲜事',
        },
        general: {
            id: 'daily-campus-mode',
            title: '日常校园奇遇',
            subtitle: '去别处看看新的奇遇吧',
        },
    },
}

const specialAreas = [
    {
        id: 'center',
        name: '中间',
        color: '#BFEA7C',
        desc: '校园主舞台与人气活动聚集地',
    },
    {
        id: 'west',
        name: '西边',
        color: '#A9DDF7',
        desc: '草地与生活区，适合慢慢探索',
    },
    {
        id: 'east',
        name: '东边',
        color: '#F7D85E',
        desc: '学术与社团互动密集区',
    },
]

const specialLocations = [
    {
        id: 'zhongcao',
        areaId: 'center',
        name: '中操',
        shortDesc: '草地舞台和快闪常驻点',
        color: '#BFEA7C',
        x: 46,
        y: 56,
        isHot: true,
    },
    {
        id: 'student-center',
        areaId: 'center',
        name: '大学生活动中心',
        shortDesc: '室内展演与宣讲集中地',
        color: '#DDF3B2',
        x: 57,
        y: 42,
        isHot: true,
    },
    {
        id: 'xicao',
        areaId: 'west',
        name: '西操',
        shortDesc: '夜间运动和表演都很热闹',
        color: '#A9DDF7',
        x: 20,
        y: 52,
        isHot: true,
    },
    {
        id: 'xishier',
        areaId: 'west',
        name: '西十二',
        shortDesc: '教学楼前常有体验摊位',
        color: '#CFEFFF',
        x: 29,
        y: 67,
        isHot: false,
    },
    {
        id: 'zisong',
        areaId: 'west',
        name: '紫菘',
        shortDesc: '生活区周边，轻松又温暖',
        color: '#F6A7C8',
        x: 30,
        y: 34,
        isHot: false,
    },
    {
        id: 'dongjiu',
        areaId: 'east',
        name: '东九',
        shortDesc: '技术社团展示高频出现',
        color: '#F7D85E',
        x: 74,
        y: 41,
        isHot: true,
    },
    {
        id: 'yunyuan',
        areaId: 'east',
        name: '韵苑',
        shortDesc: '夜拍和互动活动氛围浓厚',
        color: '#FFD980',
        x: 79,
        y: 62,
        isHot: false,
    },
    {
        id: 'southgate',
        areaId: 'east',
        name: '南大门',
        shortDesc: '观星、迎新和大路演热门点位',
        color: '#FFE9A8',
        x: 64,
        y: 80,
        isHot: true,
    },
]

const specialEvents = [
    {
        id: 'e001',
        title: '吉他社草地弹唱',
        club: '微风吉他社',
        category: '文艺',
        areaId: 'center',
        areaName: '中间',
        locationId: 'zhongcao',
        locationName: '中操',
        time: '周三 18:30-20:00',
        tags: ['轻音乐', '互动点歌'],
        shortDesc: '草地晚风里听一首熟悉旋律。',
        detailDesc: '吉他社带来轻松弹唱专场，现场可点歌并开放新成员体验，零基础也能加入合奏角。',
        highlight: '现场点歌 + 新手体验位',
        suitable: '喜欢音乐、想尝试舞台表达的同学',
        joinWay: '到场签到后排队体验，关注社团群获取曲目单',
        coverColor: '#BFEA7C',
        coverImage: '',
    },
    {
        id: 'e002',
        title: '轮滑社体验夜滑',
        club: '飞轮轮滑社',
        category: '体育',
        areaId: 'west',
        areaName: '西边',
        locationId: 'xicao',
        locationName: '西操',
        time: '周五 19:00-21:00',
        tags: ['夜滑', '入门教学'],
        shortDesc: '和微仔一起学会第一圈夜滑。',
        detailDesc: '轮滑社安排分层教学，提供基础护具体验和技巧展示，初学者有专门教练带队。',
        highlight: '分层教学 + 护具体验',
        suitable: '想锻炼平衡感和运动胆量的同学',
        joinWay: '现场填写体验卡，穿运动装即可参与',
        coverColor: '#A9DDF7',
        coverImage: '',
    },
    {
        id: 'e003',
        title: '辩论队开放交流',
        club: '思辨辩论队',
        category: '学术',
        areaId: 'center',
        areaName: '中间',
        locationId: 'student-center',
        locationName: '大学生活动中心',
        time: '周四 19:00-20:30',
        tags: ['公开题', '思维训练'],
        shortDesc: '一句问题，点燃一整晚思辨火花。',
        detailDesc: '辩论队开放队内训练流程，现场体验立论、盘问与自由辩，欢迎跨专业旁听。',
        highlight: '实战式公开训练',
        suitable: '喜欢表达、逻辑分析和公共议题的同学',
        joinWay: '扫码报名试听，活动当天提前15分钟签到',
        coverColor: '#F7D85E',
        coverImage: '',
    },
    {
        id: 'e004',
        title: '汉服社文化体验',
        club: '华章汉服社',
        category: '文艺',
        areaId: 'west',
        areaName: '西边',
        locationId: 'zisong',
        locationName: '紫菘',
        time: '周六 15:00-17:00',
        tags: ['妆造', '礼仪'],
        shortDesc: '试一袭衣冠，遇见传统文化之美。',
        detailDesc: '汉服社带来形制讲解与基础礼仪体验，提供拍照打卡角，了解社团日常活动安排。',
        highlight: '形制讲解 + 打卡拍照角',
        suitable: '对传统文化和摄影打卡感兴趣的同学',
        joinWay: '现场排号体验，建议提前线上预约',
        coverColor: '#F6A7C8',
        coverImage: '',
    },
    {
        id: 'e005',
        title: '机器人社作品展示',
        club: '智创机器人社',
        category: '技术',
        areaId: 'east',
        areaName: '东边',
        locationId: 'dongjiu',
        locationName: '东九',
        time: '周二 14:30-17:00',
        tags: ['机器人', '项目展示'],
        shortDesc: '让创意动起来，看看机械小伙伴。',
        detailDesc: '机器人社展示历年竞赛项目，开放基础传感器体验台和编程问答，适合零基础入门。',
        highlight: '竞赛项目近距离演示',
        suitable: '对工程、编程、硬件感兴趣的同学',
        joinWay: '现场登记方向偏好，后续安排体验工作坊',
        coverColor: '#8CCB5E',
        coverImage: '',
    },
    {
        id: 'e006',
        title: '街舞社快闪',
        club: '律动街舞社',
        category: '体育',
        areaId: 'east',
        areaName: '东边',
        locationId: 'southgate',
        locationName: '南大门',
        time: '周三 17:40-18:20',
        tags: ['快闪', '编舞教学'],
        shortDesc: '跟上节拍，和微仔一起摇摆。',
        detailDesc: '街舞社带来主题快闪并开放基础动作教学，活动后可加入体验训练营。',
        highlight: '现场快闪 + 动作教学',
        suitable: '喜欢音乐节奏和团队表演的同学',
        joinWay: '到场即可加入，运动鞋更方便',
        coverColor: '#A9DDF7',
        coverImage: '',
    },
    {
        id: 'e007',
        title: '摄影协会夜拍',
        club: '光影摄影协会',
        category: '文艺',
        areaId: 'east',
        areaName: '东边',
        locationId: 'yunyuan',
        locationName: '韵苑',
        time: '周五 20:00-21:30',
        tags: ['夜景', '构图'],
        shortDesc: '用镜头收集夜色里的校园故事。',
        detailDesc: '摄影协会分享夜景拍摄思路，带队实拍并现场点评，手机和相机都可参与。',
        highlight: '边走边拍 + 即时点评',
        suitable: '喜欢记录生活和视觉表达的同学',
        joinWay: '关注报名表后进群，按集合点签到',
        coverColor: '#F7D85E',
        coverImage: '',
    },
    {
        id: 'e008',
        title: '桌游社试玩派对',
        club: '星火桌游社',
        category: '综合',
        areaId: 'west',
        areaName: '西边',
        locationId: 'xishier',
        locationName: '西十二',
        time: '周日 14:00-17:00',
        tags: ['策略', '社交'],
        shortDesc: '轻松入局，认识更多有趣同伴。',
        detailDesc: '桌游社准备了轻策略与欢乐向桌游，设有新手引导桌，单人到场也能快速组队。',
        highlight: '新手友好 + 快速组桌',
        suitable: '想拓展社交圈、喜欢推理策略的同学',
        joinWay: '现场登记游戏偏好后匹配桌组',
        coverColor: '#FFD980',
        coverImage: '',
    },
    {
        id: 'e009',
        title: '志愿服务协会招新宣讲',
        club: '暖阳志愿服务协会',
        category: '公益',
        areaId: 'center',
        areaName: '中间',
        locationId: 'student-center',
        locationName: '大学生活动中心',
        time: '周一 16:00-17:30',
        tags: ['志愿', '宣讲'],
        shortDesc: '把温暖变成行动，一起去发光。',
        detailDesc: '协会介绍社区服务、支教和校园活动项目，公开报名流程与学期志愿计划。',
        highlight: '项目介绍 + 路线规划',
        suitable: '有公益热情、愿意长期参与服务的同学',
        joinWay: '填写志愿方向问卷后加入项目群',
        coverColor: '#BFEA7C',
        coverImage: '',
    },
    {
        id: 'e010',
        title: '心理协会解压互动',
        club: '心晴心理协会',
        category: '公益',
        areaId: 'east',
        areaName: '东边',
        locationId: 'yunyuan',
        locationName: '韵苑',
        time: '周四 18:00-19:30',
        tags: ['解压', '互动'],
        shortDesc: '给忙碌的你一个轻轻呼吸的角落。',
        detailDesc: '心理协会设置情绪减压小游戏和倾听角，分享校园压力管理小技巧。',
        highlight: '互动解压 + 情绪小贴士',
        suitable: '希望缓解压力、提升自我照顾能力的同学',
        joinWay: '现场自由参与，无需提前准备',
        coverColor: '#F6A7C8',
        coverImage: '',
    },
    {
        id: 'e011',
        title: '戏剧社片段展演',
        club: '未央戏剧社',
        category: '文艺',
        areaId: 'west',
        areaName: '西边',
        locationId: 'xicao',
        locationName: '西操',
        time: '周六 19:30-20:40',
        tags: ['表演', '台词体验'],
        shortDesc: '一段故事，点亮今晚的舞台。',
        detailDesc: '戏剧社带来经典剧目片段展演，开放台词体验和即兴互动，感受舞台魅力。',
        highlight: '经典片段 + 即兴互动',
        suitable: '对表演表达、舞台艺术感兴趣的同学',
        joinWay: '活动后可登记参加新生工作坊',
        coverColor: '#A9DDF7',
        coverImage: '',
    },
    {
        id: 'e012',
        title: '天文协会观星分享',
        club: '逐星天文协会',
        category: '学术',
        areaId: 'east',
        areaName: '东边',
        locationId: 'southgate',
        locationName: '南大门',
        time: '周日 20:00-22:00',
        tags: ['观星', '望远镜体验'],
        shortDesc: '抬头看星空，低头许下新愿望。',
        detailDesc: '天文协会分享当季可观测天体，现场搭设望远镜体验点，并讲解基础星图识读方法。',
        highlight: '望远镜实测 + 星图教学',
        suitable: '对宇宙和自然科学有好奇心的同学',
        joinWay: '关注天气预告，按通知时间集合',
        coverColor: '#8CCB5E',
        coverImage: '',
    },
]

const generalAreas = [
    {
        id: 'center',
        name: '中间',
        color: '#BFEA7C',
        desc: '通用版主线导览区，日常活动更新快',
    },
    {
        id: 'west',
        name: '西边',
        color: '#A9DDF7',
        desc: '生活与运动线并行，轻松社交更集中',
    },
    {
        id: 'east',
        name: '东边',
        color: '#F7D85E',
        desc: '技术与学术线密集，适合深度探索',
    },
]

const generalLocations = [
    {
        id: 'zhongcao',
        areaId: 'center',
        name: '中操',
        shortDesc: '日常社团打卡和轻演出高频点',
        color: '#BFEA7C',
        x: 46,
        y: 56,
        isHot: true,
    },
    {
        id: 'student-center',
        areaId: 'center',
        name: '大学生活动中心',
        shortDesc: '讲座、工作坊和报名咨询集中区',
        color: '#DDF3B2',
        x: 57,
        y: 42,
        isHot: true,
    },
    {
        id: 'xicao',
        areaId: 'west',
        name: '西操',
        shortDesc: '运动社团训练与体验活动常驻',
        color: '#A9DDF7',
        x: 20,
        y: 52,
        isHot: true,
    },
    {
        id: 'xishier',
        areaId: 'west',
        name: '西十二',
        shortDesc: '午后社团快闪与试玩活动聚点',
        color: '#CFEFFF',
        x: 29,
        y: 67,
        isHot: false,
    },
    {
        id: 'zisong',
        areaId: 'west',
        name: '紫菘',
        shortDesc: '生活区慢节奏互动和兴趣体验区',
        color: '#F6A7C8',
        x: 30,
        y: 34,
        isHot: false,
    },
    {
        id: 'dongjiu',
        areaId: 'east',
        name: '东九',
        shortDesc: '技术类社团开放工位与项目展示区',
        color: '#F7D85E',
        x: 74,
        y: 41,
        isHot: true,
    },
    {
        id: 'yunyuan',
        areaId: 'east',
        name: '韵苑',
        shortDesc: '夜间轻活动和休闲社群互动点',
        color: '#FFD980',
        x: 79,
        y: 62,
        isHot: false,
    },
    {
        id: 'southgate',
        areaId: 'east',
        name: '南大门',
        shortDesc: '迎新导览与大型路演常驻入口位',
        color: '#FFE9A8',
        x: 64,
        y: 80,
        isHot: true,
    },
]

const generalEvents = [
    {
        id: 'g001',
        title: '晨光合唱快练',
        club: '拾光合唱团',
        category: '文艺',
        areaId: 'center',
        areaName: '中间',
        locationId: 'zhongcao',
        locationName: '中操',
        time: '周二 07:10-07:50',
        tags: ['晨练', '和声体验'],
        shortDesc: '早八前来一段合唱热身，整天都更有元气。',
        detailDesc: '合唱团开放晨间基础发声与和声体验，适合想培养节奏感和舞台默契的同学。',
        highlight: '短时高效发声训练',
        suitable: '想提升声乐基础、希望结识音乐搭子的同学',
        joinWay: '到场签到即可参与，建议提前5分钟到',
        coverColor: '#BFEA7C',
        coverImage: '',
    },
    {
        id: 'g002',
        title: '羽毛球晨练搭子局',
        club: '轻羽社',
        category: '体育',
        areaId: 'west',
        areaName: '西边',
        locationId: 'xicao',
        locationName: '西操',
        time: '周三 07:00-08:00',
        tags: ['晨练', '双打组队'],
        shortDesc: '不必一个人晨练，来这里快速匹配运动搭子。',
        detailDesc: '轻羽社提供基础热身指导与双打轮换机制，帮助新手在轻松氛围中完成第一场对练。',
        highlight: '现场组队 + 新手友好',
        suitable: '想规律运动、需要伙伴激励的同学',
        joinWay: '到场登记水平等级后分组开打',
        coverColor: '#A9DDF7',
        coverImage: '',
    },
    {
        id: 'g003',
        title: '数据结构互助问答站',
        club: '算法学习社',
        category: '学术',
        areaId: 'east',
        areaName: '东边',
        locationId: 'dongjiu',
        locationName: '东九',
        time: '周四 19:00-20:30',
        tags: ['刷题', '答疑'],
        shortDesc: '带着卡住的问题来，带着思路回去。',
        detailDesc: '算法学习社会安排学长学姐轮值答疑，覆盖链表、树、图等常见问题与学习路径建议。',
        highlight: '现场拆题 + 学习路径建议',
        suitable: '正在准备课程作业或竞赛入门的同学',
        joinWay: '现场排号提问，建议自带纸笔或平板',
        coverColor: '#F7D85E',
        coverImage: '',
    },
    {
        id: 'g004',
        title: '校园植物写生角',
        club: '手绘与插画社',
        category: '文艺',
        areaId: 'west',
        areaName: '西边',
        locationId: 'zisong',
        locationName: '紫菘',
        time: '周六 16:00-18:00',
        tags: ['写生', '速写'],
        shortDesc: '带上一支笔，把春天装进你的速写本。',
        detailDesc: '插画社提供基础构图指导和写生主题卡，帮助参与者完成一幅可带走的校园植物小作品。',
        highlight: '现场写生 + 作品小展',
        suitable: '喜欢手绘、想尝试慢节奏创作的同学',
        joinWay: '可自带画材，也可现场借用基础工具',
        coverColor: '#F6A7C8',
        coverImage: '',
    },
    {
        id: 'g005',
        title: '创客开放工位',
        club: '未来创客社',
        category: '技术',
        areaId: 'east',
        areaName: '东边',
        locationId: 'dongjiu',
        locationName: '东九',
        time: '周二 18:30-21:00',
        tags: ['开源项目', '协作'],
        shortDesc: '把想法带来，现场就能找到合作伙伴。',
        detailDesc: '创客社开放社团工位，提供硬件打样与前后端协作答疑，鼓励跨专业组队孵化小项目。',
        highlight: '开放工位 + 项目共创',
        suitable: '有技术兴趣、想找队友做项目的同学',
        joinWay: '报名后进入协作群，现场领取工位号',
        coverColor: '#8CCB5E',
        coverImage: '',
    },
    {
        id: 'g006',
        title: '午间减压补给站',
        club: '心晴心理协会',
        category: '公益',
        areaId: 'center',
        areaName: '中间',
        locationId: 'student-center',
        locationName: '大学生活动中心',
        time: '周一 12:10-13:20',
        tags: ['情绪调节', '放松训练'],
        shortDesc: '午休的 20 分钟，也能让心情慢慢回温。',
        detailDesc: '心理协会推出午间轻量放松流程，包括呼吸练习、解压手作和短时情绪梳理环节。',
        highlight: '短时放松流程 + 解压手作',
        suitable: '课程紧张、想快速恢复状态的同学',
        joinWay: '无需预约，现场按批次入场体验',
        coverColor: '#F6A7C8',
        coverImage: '',
    },
    {
        id: 'g007',
        title: '社区志愿排班说明会',
        club: '暖阳志愿服务协会',
        category: '公益',
        areaId: 'east',
        areaName: '东边',
        locationId: 'southgate',
        locationName: '南大门',
        time: '周四 17:20-18:20',
        tags: ['排班', '社区服务'],
        shortDesc: '从一次小时服务开始，慢慢累积你的善意轨迹。',
        detailDesc: '协会公开本学期志愿岗位与时间排班，现场说明不同项目的参与门槛与成长路径。',
        highlight: '岗位说明 + 灵活排班',
        suitable: '想稳定参与公益、安排固定服务时段的同学',
        joinWay: '现场填写意向表，后续按方向分组',
        coverColor: '#BFEA7C',
        coverImage: '',
    },
    {
        id: 'g008',
        title: '桌游午后轻社交',
        club: '星火桌游社',
        category: '综合',
        areaId: 'west',
        areaName: '西边',
        locationId: 'xishier',
        locationName: '西十二',
        time: '周日 14:00-16:30',
        tags: ['轻社交', '欢乐局'],
        shortDesc: '一个人来也没关系，三分钟就能开一桌。',
        detailDesc: '桌游社设置新手速配桌和进阶策略桌，主持人带节奏，帮助新人快速融入。',
        highlight: '主持带局 + 快速破冰',
        suitable: '想认识新朋友、偏好轻松互动的同学',
        joinWay: '到场领取颜色贴纸后按偏好入桌',
        coverColor: '#FFD980',
        coverImage: '',
    },
    {
        id: 'g009',
        title: '电影配音体验夜',
        club: '声景配音社',
        category: '文艺',
        areaId: 'center',
        areaName: '中间',
        locationId: 'student-center',
        locationName: '大学生活动中心',
        time: '周五 19:00-21:00',
        tags: ['配音', '台词'],
        shortDesc: '挑一段你熟悉的桥段，试一次主角声线。',
        detailDesc: '配音社提供经典片段和录音体验位，现场可领取个人语音片段并获得基础点评。',
        highlight: '录音体验 + 个性化点评',
        suitable: '喜欢声音表达、想提升普通话与情感表达的同学',
        joinWay: '现场预约片段时段，按号体验',
        coverColor: '#A9DDF7',
        coverImage: '',
    },
    {
        id: 'g010',
        title: '跑团故事开箱夜',
        club: '想象力跑团社',
        category: '综合',
        areaId: 'east',
        areaName: '东边',
        locationId: 'yunyuan',
        locationName: '韵苑',
        time: '周六 19:30-22:00',
        tags: ['TRPG', '叙事'],
        shortDesc: '在一场冒险里，认识另一种自己。',
        detailDesc: '跑团社提供新手剧情本和主持入门讲解，参与者可选择角色并完成一段短篇故事。',
        highlight: '新手剧情本 + 主持引导',
        suitable: '喜欢剧情、角色扮演和团队协作的同学',
        joinWay: '提前线上选角，现场按房间分组',
        coverColor: '#F7D85E',
        coverImage: '',
    },
    {
        id: 'g011',
        title: '科创路演彩排场',
        club: '大学生科创中心',
        category: '技术',
        areaId: 'center',
        areaName: '中间',
        locationId: 'zhongcao',
        locationName: '中操',
        time: '周三 16:30-18:00',
        tags: ['路演', '表达训练'],
        shortDesc: '项目不只要做出来，也要讲得清楚。',
        detailDesc: '科创中心组织路演模拟，提供 3 分钟项目阐述模板和导师反馈，帮助准备竞赛展示。',
        highlight: '路演模板 + 导师反馈',
        suitable: '有项目成果、需要提升展示表达的同学',
        joinWay: '提前上传项目摘要，现场分组演练',
        coverColor: '#8CCB5E',
        coverImage: '',
    },
    {
        id: 'g012',
        title: '观云与气象小课堂',
        club: '逐星天文协会',
        category: '学术',
        areaId: 'east',
        areaName: '东边',
        locationId: 'southgate',
        locationName: '南大门',
        time: '周日 17:00-18:20',
        tags: ['气象', '观测'],
        shortDesc: '抬头看云，也能读出天气背后的规律。',
        detailDesc: '天文协会带来基础云型识别和简易观测记录方法，适合想入门自然观测的同学。',
        highlight: '云型识别 + 观测记录入门',
        suitable: '对自然科学和户外观测感兴趣的同学',
        joinWay: '到场领取观测卡，跟随讲解完成实践',
        coverColor: '#F7D85E',
        coverImage: '',
    },
]

const modeDataMap = {
    special: {
        areas: specialAreas,
        locations: specialLocations,
        events: specialEvents,
    },
    general: {
        areas: generalAreas,
        locations: generalLocations,
        events: generalEvents,
    },
}

const categoryOptions = ['全部', '文艺', '体育', '学术', '公益', '技术', '综合']

function normalizeMode(mode) {
    return mode === 'general' ? 'general' : 'special'
}

function getTopicConfig(mode = appConfig.mode) {
    const normalizedMode = normalizeMode(mode)
    return appConfig.topicConfigs[normalizedMode] || appConfig.topicConfigs.special
}

function getDataBundle(mode = appConfig.mode) {
    const normalizedMode = normalizeMode(mode)
    const source = modeDataMap[normalizedMode] || modeDataMap.special
    return {
        mode: normalizedMode,
        topic: getTopicConfig(normalizedMode),
        areas: source.areas,
        locations: source.locations,
        events: source.events,
    }
}

function getAreaById(areaId, mode = appConfig.mode) {
    return getDataBundle(mode).areas.find((item) => item.id === areaId) || null
}

function getLocationById(locationId, mode = appConfig.mode) {
    return getDataBundle(mode).locations.find((item) => item.id === locationId) || null
}

function getEventById(eventId, mode = appConfig.mode) {
    return getDataBundle(mode).events.find((item) => item.id === eventId) || null
}

function getLocationsByArea(areaId, mode = appConfig.mode) {
    return getDataBundle(mode).locations.filter((item) => item.areaId === areaId)
}

function getEventsByLocation(locationId, mode = appConfig.mode) {
    return getDataBundle(mode).events.filter((item) => item.locationId === locationId)
}

function getLocationByIdAcrossModes(locationId) {
    return specialLocations.find((item) => item.id === locationId) || generalLocations.find((item) => item.id === locationId) || null
}

function getEventByIdAcrossModes(eventId) {
    return specialEvents.find((item) => item.id === eventId) || generalEvents.find((item) => item.id === eventId) || null
}

const areas = specialAreas
const locations = specialLocations
const events = specialEvents

module.exports = {
    appConfig,
    areas,
    locations,
    events,
    categoryOptions,
    normalizeMode,
    getTopicConfig,
    getDataBundle,
    getAreaById,
    getLocationById,
    getEventById,
    getLocationsByArea,
    getEventsByLocation,
    getLocationByIdAcrossModes,
    getEventByIdAcrossModes,
}
